### ISSUE TITLE
c.TplNames undefined

### ISSUE THREAD

**Issue by zcalusic** [kenshinx/joke#3]
Does not compile, with error:
```
controllers/dns.go:45: c.TplNames undefined (type *DNSController has no field or method TplNames)
```

**Comment by nikkiii** [comment]
This looks like an issue with versions, if you're still interested.

From the beego docs:
`From version 1.6: this.TplNames is this.TplName`

Just modify line 45 of `controllers/dns.go` from `c.TplNames` to `c.TplName`

**Comment by kenshinx** [comment]
Sorry, i almost forgot this open issue.
As @nikkiii  pointed out this is caused by beego syntax changed in v1.6.
I have fixed this issue just now.
